name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install project
        run: |
          yarn install --frozen-lockfile
      - name: Build
        run: |
          yarn build
      - name: Test
        run: |
          yarn test
